// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto1_Web2_IF_johnnata.Models;

#nullable disable

namespace Projeto1_Web2_IF_Johnnata.Migrations
{
    [DbContext(typeof(db_ifContext))]
    [Migration("20260629160325_InitialCreateDbIf")]
    partial class InitialCreateDbIf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetRolesAspNetUsers", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("AspNetRolesAspNetUsers");
                });

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetRoleClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUserLogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUserTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbAlimento", b =>
                {
                    b.Property<int>("IdAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlimento"));

                    b.Property<double>("Carboidrato")
                        .HasColumnType("float");

                    b.Property<int>("IdTipoQuantidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("VitaminaA")
                        .HasColumnType("float");

                    b.Property<double>("VitaminaB")
                        .HasColumnType("float");

                    b.HasKey("IdAlimento")
                        .HasName("PK__tbAlimen__2406570577A5EC2C");

                    b.ToTable("tbAlimento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbAntropometria", b =>
                {
                    b.Property<int>("IdAntropometria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAntropometria"));

                    b.Property<int?>("Abdomen")
                        .HasColumnType("int");

                    b.Property<int?>("AlturaJoelho")
                        .HasColumnType("int");

                    b.Property<int?>("AuxiliarMed")
                        .HasColumnType("int");

                    b.Property<int?>("Biceps")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfAbdomen")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfBraco")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfCintura")
                        .HasColumnType("int");

                    b.Property<int?>("CircunfQuadril")
                        .HasColumnType("int");

                    b.Property<int?>("Coxa")
                        .HasColumnType("int");

                    b.Property<int?>("Estatura")
                        .HasColumnType("int");

                    b.Property<int>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("Panturrilha")
                        .HasColumnType("int");

                    b.Property<int?>("Peitoral")
                        .HasColumnType("int");

                    b.Property<int?>("PercGordura")
                        .HasColumnType("int");

                    b.Property<int?>("PesoAtual")
                        .HasColumnType("int");

                    b.Property<int?>("PesoUsual")
                        .HasColumnType("int");

                    b.Property<int?>("Subescap")
                        .HasColumnType("int");

                    b.Property<int?>("SupraIliaca")
                        .HasColumnType("int");

                    b.Property<int?>("TipoProtocolo")
                        .HasColumnType("int");

                    b.Property<int?>("Tricipal")
                        .HasColumnType("int");

                    b.HasKey("IdAntropometria")
                        .HasName("PK__tbAntrop__53A9E5941381DBE2");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbAntropometria_IdHoraPaciente_Profissional");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbAntropometria_IdPaciente");

                    b.ToTable("tbAntropometria");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbCategoriaMedicamento", b =>
                {
                    b.Property<int>("IdCategoriaMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaMedicamento"));

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCategoriaMedicamento")
                        .HasName("PK__tbCatego__14A80672AD9984E8");

                    b.ToTable("tbCategoriaMedicamento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbCidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdCidade")
                        .HasName("PK__tbCidade__160879A3F9A62446");

                    b.HasIndex(new[] { "IdEstado" }, "IX_tbCidade_IdEstado");

                    b.ToTable("tbCidade");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbContrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("IdPlano")
                        .HasColumnType("int");

                    b.HasKey("IdContrato")
                        .HasName("PK__tbContra__8569F05AC291EB56");

                    b.HasIndex(new[] { "IdPlano" }, "IX_tbContrato_IdPlano");

                    b.ToTable("tbContrato");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEscalaBristol", b =>
                {
                    b.Property<int>("IdEscalaBristol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscalaBristol"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Sangue")
                        .HasColumnType("bit");

                    b.HasKey("IdEscalaBristol")
                        .HasName("PK__tbEscala__A6FB417FE5BEBAC8");

                    b.ToTable("tbEscalaBristol");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEscalaBristolPacienteConsulta", b =>
                {
                    b.Property<int>("IdEscalaBristolPacienteConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEscalaBristol_Paciente_Consulta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscalaBristolPacienteConsulta"));

                    b.Property<int>("IdEscalaBristol")
                        .HasColumnType("int");

                    b.Property<int>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHora_Paciente_Profissional");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("IdEscalaBristolPacienteConsulta")
                        .HasName("PK__tbEscala__44B7B8966A35F545");

                    b.HasIndex(new[] { "IdEscalaBristol" }, "IX_tbEscalaBristol_Paciente_Consulta_IdEscalaBristol");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbEscalaBristol_Paciente_Consulta_IdHora_Paciente_Profissional");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbEscalaBristol_Paciente_Consulta_IdPaciente");

                    b.ToTable("tbEscalaBristol_Paciente_Consulta");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEstado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("IdEstado")
                        .HasName("PK__tbEstado__FBB0EDC188F0ED55");

                    b.HasIndex(new[] { "IdPais" }, "IX_tbEstado_IdPais");

                    b.ToTable("tbEstado");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbExame", b =>
                {
                    b.Property<int>("IdExame")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExame"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Grupo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdExame")
                        .HasName("PK__tbExame__0C2F360F255CCA14");

                    b.ToTable("tbExame");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbExameFisico", b =>
                {
                    b.Property<int>("IdExameFisico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExameFisico"));

                    b.Property<int?>("AtividadeFisica")
                        .HasColumnType("int");

                    b.Property<int?>("Diurese")
                        .HasColumnType("int");

                    b.Property<int?>("Evacuacao")
                        .HasColumnType("int");

                    b.Property<int?>("Excrecao")
                        .HasColumnType("int");

                    b.Property<bool?>("FlgDenticaoAusente")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDenticaoCompleta")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDenticaoIncompleta")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDenticaoProtese")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDisfagia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDuodenal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgEnteralExclusiva")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgEnteralParental")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgFistula")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgGastrico")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHiperemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgJejunal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgNauseas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOdinofagia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOral")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOralEnteral")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgParentalExclusiva")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgParentalOral")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPresencaFeridas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgSaidaSecrecao")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgSialorreia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgTranspilorica")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgUlcerasBucais")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgVomitos")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgXerostomia")
                        .HasColumnType("bit");

                    b.Property<int?>("Frequencia")
                        .HasColumnType("int");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int?>("FrequenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<int?>("Fumante")
                        .HasColumnType("int");

                    b.Property<int?>("Glicemia")
                        .HasColumnType("int");

                    b.Property<int?>("HoraPreferido")
                        .HasColumnType("int");

                    b.Property<int?>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    b.Property<int?>("Ingestao")
                        .HasColumnType("int");

                    b.Property<int?>("Mastigacao")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Pa")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PA");

                    b.Property<int?>("Peristalse")
                        .HasColumnType("int");

                    b.Property<int?>("Snc")
                        .HasColumnType("int")
                        .HasColumnName("SNC");

                    b.Property<int?>("Temperatura")
                        .HasColumnType("int");

                    b.Property<int?>("Tempo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoAcesso")
                        .HasColumnType("int");

                    b.Property<string>("TipoAtividadeFisica")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("TipoDiurese")
                        .HasColumnType("int");

                    b.Property<int?>("TipoEvacuacao")
                        .HasColumnType("int");

                    b.HasKey("IdExameFisico")
                        .HasName("PK__tbExameF__C8897518CD27158B");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbExameFisico_IdHoraPaciente_Profissional");

                    b.ToTable("tbExameFisico");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbExameXPacientes", b =>
                {
                    b.Property<int>("IdExameXPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdExame_X_Paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExameXPaciente"));

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdExame")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("IdExameXPaciente")
                        .HasName("PK__tbExame___8F261547D75B06D7");

                    b.HasIndex(new[] { "IdExame" }, "IX_tbExame_X_Pacientes_IdExame");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbExame_X_Pacientes_IdPaciente");

                    b.ToTable("tbExame_X_Pacientes");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbGrupoPatologico", b =>
                {
                    b.Property<int>("IdGrupoPatologico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoPatologico"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdGrupoPatologico")
                        .HasName("PK__tbGrupoP__A7D4244D8473F997");

                    b.ToTable("tbGrupoPatologico");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbGrupoPatologicoXPatologia", b =>
                {
                    b.Property<int>("IdPatologiaXGrupoPatologico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPatologia_X_GrupoPatologico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatologiaXGrupoPatologico"));

                    b.Property<int>("IdGrupoPatologico")
                        .HasColumnType("int");

                    b.Property<int>("IdPatologia")
                        .HasColumnType("int");

                    b.HasKey("IdPatologiaXGrupoPatologico")
                        .HasName("PK__tbGrupoP__2BA30300C74D500A");

                    b.HasIndex(new[] { "IdGrupoPatologico" }, "IX_tbGrupoPatologico_X_Patologia_IdGrupoPatologico");

                    b.HasIndex(new[] { "IdPatologia" }, "IX_tbGrupoPatologico_X_Patologia_IdPatologia");

                    b.ToTable("tbGrupoPatologico_X_Patologia");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbGruposReceitasDespesas", b =>
                {
                    b.Property<int>("IdReceitaDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaDespesa"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdReceitaDespesa")
                        .HasName("PK__tbGrupos__6D0EB5405BF2A8A2");

                    b.ToTable("tbGruposReceitasDespesas");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoriaPatologica", b =>
                {
                    b.Property<int>("IdHistoriaPatologica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoriaPatologica"));

                    b.Property<bool?>("FlgAnemias")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvc")
                        .HasColumnType("bit")
                        .HasColumnName("FlgAVC");

                    b.Property<bool?>("FlgCirurgias")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencaHepatica")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencaRenal")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencasAutoImunes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencasCardiacas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgDoencasPulmonares")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHas")
                        .HasColumnType("bit")
                        .HasColumnName("FlgHAS");

                    b.Property<bool?>("FlgHipercolesterolemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHipertrigliciridemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgHiperuricemia")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgNeoplasia")
                        .HasColumnType("bit");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatologia")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdHistoriaPatologica")
                        .HasName("PK__tbHistor__86BDE8CF1E996F4D");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoriaPatologica_IdPaciente");

                    b.HasIndex(new[] { "IdPatologia" }, "IX_tbHistoriaPatologica_IdPatologia");

                    b.ToTable("tbHistoriaPatologica");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoricoAlimentarNutricional", b =>
                {
                    b.Property<int>("IdHistAlimentarNutricional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistAlimentarNutricional"));

                    b.Property<string>("DescDietas")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescExercicios")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescIntoleranciaAlimentar")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescMedicamentos")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescOutros")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("FaseObesidadePerdaPeso")
                        .HasColumnType("int");

                    b.Property<bool?>("FlgDietas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgExercicios")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIntoleanciaAlimentar")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgMedicamentos")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgOutros")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPerdaGanhoPeso")
                        .HasColumnType("bit");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("ModismosAlimentares")
                        .HasColumnType("int");

                    b.Property<int?>("MotivacaoTratamento")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PesoMax")
                        .HasColumnType("int");

                    b.Property<int?>("PesoMaxIdade")
                        .HasColumnType("int");

                    b.Property<int?>("PesoMin")
                        .HasColumnType("int");

                    b.Property<int?>("PesoMinIdade")
                        .HasColumnType("int");

                    b.HasKey("IdHistAlimentarNutricional")
                        .HasName("PK__tbHistor__43605910B8D41005");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoricoAlimentarNutricional_IdPaciente");

                    b.ToTable("tbHistoricoAlimentarNutricional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoricoDoencaAtual", b =>
                {
                    b.Property<int>("IdHda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHDA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHda"));

                    b.Property<int?>("Cirurgia")
                        .HasColumnType("int");

                    b.Property<string>("Historico")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatologia")
                        .HasColumnType("int");

                    b.Property<int?>("Infeccao")
                        .HasColumnType("int");

                    b.Property<int?>("Metastase")
                        .HasColumnType("int");

                    b.Property<int?>("Neoplasia")
                        .HasColumnType("int");

                    b.Property<string>("ObsMetastase")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ObsNeoplasia")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ObsQueimadura")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Outros")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Queimadura")
                        .HasColumnType("int");

                    b.Property<int?>("Trauma")
                        .HasColumnType("int");

                    b.HasKey("IdHda")
                        .HasName("PK__tbHistor__0B5E79E21AD7740A");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoricoDoencaAtual_IdPaciente");

                    b.HasIndex(new[] { "IdPatologia" }, "IX_tbHistoricoDoencaAtual_IdPatologia");

                    b.ToTable("tbHistoricoDoencaAtual");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoricoSocialAlimentar", b =>
                {
                    b.Property<int>("IdHistSocialAlimentar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistSocialAlimentar"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int?>("CompraFeita")
                        .HasColumnType("int");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("FlgAvosCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvosDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvosHas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgAvosObesidade")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgCafe")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgEtilismo")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosHas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgIrmaosObesidade")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeCancer")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeHas")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgPaiMaeObesidade")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgTabagismo")
                        .HasColumnType("bit");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompraAlimento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeCozinhaAlimento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeRealizaRefeicao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NroPessoasRes")
                        .HasColumnType("int");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("QtdCafeDia")
                        .HasColumnType("int");

                    b.Property<int?>("QtdEtilismoDia")
                        .HasColumnType("int");

                    b.Property<int?>("QtdTabagismoDia")
                        .HasColumnType("int");

                    b.Property<decimal?>("RendaFamiliar")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("IdHistSocialAlimentar")
                        .HasName("PK__tbHistor__7735810FEB315D96");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHistoricoSocialAlimentar_IdPaciente");

                    b.ToTable("tbHistoricoSocialAlimentar");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", b =>
                {
                    b.Property<int>("IdHoraPacienteProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoraPacienteProfissional"));

                    b.Property<bool>("Compareceu")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DataConsulta")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFimIndividual")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("HoraInicioIndividual")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<bool>("PrimeiraConculta")
                        .HasColumnType("bit");

                    b.Property<string>("Resumo")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdHoraPacienteProfissional")
                        .HasName("PK__tbHoraPa__A67184260E014819");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbHoraPaciente_Profissional_IdPaciente");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbHoraPaciente_Profissional_IdProfissional");

                    b.ToTable("tbHoraPaciente_Profissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbLancarReceitasDespesas", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<int>("IdReceitaDespesa")
                        .HasColumnType("int");

                    b.HasKey("IdLancamento")
                        .HasName("PK__tbLancar__2E531549C4400B28");

                    b.HasIndex(new[] { "IdReceitaDespesa" }, "IX_tbLancarReceitasDespesas_IdReceitaDespesa");

                    b.ToTable("tbLancarReceitasDespesas");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbMedicamento", b =>
                {
                    b.Property<int>("IdMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicamento"));

                    b.Property<string>("Bula")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("BulaArquivo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdCategoriaMedicamento")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdMedicamento")
                        .HasName("PK__tbMedica__AC96376E90E9D5E4");

                    b.HasIndex(new[] { "IdCategoriaMedicamento" }, "IX_tbMedicamento_IdCategoriaMedicamento");

                    b.ToTable("tbMedicamento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbMedicoPaciente", b =>
                {
                    b.Property<int>("IdMedicoPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMedico_Paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicoPaciente"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoResumida")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.HasKey("IdMedicoPaciente")
                        .HasName("PK__tbMedico__1F0BE44C0A2AD1D5");

                    b.HasIndex(new[] { "IdPaciente" }, "IX_tbMedico_Paciente_IdPaciente");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbMedico_Paciente_IdProfissional");

                    b.ToTable("tbMedico_Paciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPaciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CPF");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Etnia")
                        .HasColumnType("int");

                    b.Property<bool?>("FlgAtleta")
                        .HasColumnType("bit");

                    b.Property<bool?>("FlgGestante")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Profissao")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("RG");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("TelCelular")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TelComercial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TelResidencial")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdPaciente")
                        .HasName("PK__tbPacien__C93DB49B87CE1DFE");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbPaciente_IdCidade");

                    b.ToTable("tbPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("IdPais")
                        .HasName("PK__tbPais__FC850A7B0E4B8FB8");

                    b.ToTable("tbPais");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPatologia", b =>
                {
                    b.Property<int>("IdPatologia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatologia"));

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPatologia")
                        .HasName("PK__tbPatolo__6D573A32CB2159DD");

                    b.ToTable("tbPatologia");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPergunta", b =>
                {
                    b.Property<int>("IdPergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPergunta"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdPergunta")
                        .HasName("PK__tbPergun__6DC6D9A7D4EDA3D1");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbPergunta_IdProfissional");

                    b.ToTable("tbPergunta");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPlano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Validade")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPlano")
                        .HasName("PK__tbPlano__4C970C540297154D");

                    b.ToTable("tbPlano");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbProfissional", b =>
                {
                    b.Property<int>("IdProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfissional"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CPF");

                    b.Property<string>("CrmCrn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CRM_CRN");

                    b.Property<string>("Ddd1")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("DDD1");

                    b.Property<string>("Ddd2")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("DDD2");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("IdCidade")
                        .HasColumnType("int");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoAcesso")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoProfissional")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Telefone1")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Telefone2")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdProfissional")
                        .HasName("PK__tbProfis__B9503FBCD9D3008C");

                    b.HasIndex(new[] { "IdCidade" }, "IX_tbProfissional_IdCidade");

                    b.HasIndex(new[] { "IdContrato" }, "IX_tbProfissional_IdContrato");

                    b.HasIndex(new[] { "IdTipoAcesso" }, "IX_tbProfissional_IdTipoAcesso");

                    b.ToTable("tbProfissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbRastreamentoMetabolico", b =>
                {
                    b.Property<int>("IdRastreamentoMetabolico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRastreamentoMetabolico"));

                    b.Property<int>("IdHoraPacienteProfissional")
                        .HasColumnType("int")
                        .HasColumnName("IdHoraPaciente_Profissional");

                    b.Property<int>("IdRastreamentoResposta")
                        .HasColumnType("int");

                    b.Property<string>("ObsGeral")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.HasKey("IdRastreamentoMetabolico")
                        .HasName("PK__tbRastre__E5AA062354B3AF6E");

                    b.HasIndex(new[] { "IdHoraPacienteProfissional" }, "IX_tbRastreamentoMetabolico_IdHoraPaciente_Profissional");

                    b.HasIndex(new[] { "IdRastreamentoResposta" }, "IX_tbRastreamentoMetabolico_IdRastreamentoResposta");

                    b.ToTable("tbRastreamentoMetabolico");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbRastreamentoResposta", b =>
                {
                    b.Property<int>("IdRastreamentoResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRastreamentoResposta"));

                    b.Property<int>("IdParteCorpo")
                        .HasColumnType("int");

                    b.Property<int>("IdPergunta")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("VlrRespota")
                        .HasColumnType("int");

                    b.HasKey("IdRastreamentoResposta")
                        .HasName("PK__tbRastre__ABA70EB6ADFF52D5");

                    b.HasIndex(new[] { "IdPergunta" }, "IX_tbRastreamentoResposta_IdPergunta");

                    b.ToTable("tbRastreamentoResposta");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaAlimentarPadrao", b =>
                {
                    b.Property<int>("IdReceitaAlimentarPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaAlimentarPadrao"));

                    b.Property<int?>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdReceitaAlimentarPadrao")
                        .HasName("PK__tbReceit__63863561B967240D");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbReceitaAlimentarPadrao_IdProfissional");

                    b.ToTable("tbReceitaAlimentarPadrao");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaAlimentarPadraoXAlimento", b =>
                {
                    b.Property<int>("IdReceitaAlimentarPadraoXAlimentoXQuantidadeAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdReceitaAlimentarPadrao_X_Alimento_X_QuantidadeAlimento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaAlimentarPadraoXAlimentoXQuantidadeAlimento"));

                    b.Property<int>("IdAlimento")
                        .HasColumnType("int");

                    b.Property<int>("IdQuantidadeAlimento")
                        .HasColumnType("int");

                    b.Property<int>("IdReceitaAlimentarPadrao")
                        .HasColumnType("int");

                    b.Property<string>("Periodicidade")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QuantoTempo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdReceitaAlimentarPadraoXAlimentoXQuantidadeAlimento")
                        .HasName("PK__tbReceit__2843B293137E4EBF");

                    b.HasIndex(new[] { "IdAlimento" }, "IX_tbReceitaAlimentarPadrao_X_Alimento_IdAlimento");

                    b.HasIndex(new[] { "IdReceitaAlimentarPadrao" }, "IX_tbReceitaAlimentarPadrao_X_Alimento_IdReceitaAlimentarPadrao");

                    b.ToTable("tbReceitaAlimentarPadrao_X_Alimento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaMedicaPadrao", b =>
                {
                    b.Property<int>("IdReceitaMedicaPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceitaMedicaPadrao"));

                    b.Property<int>("IdProfissional")
                        .HasColumnType("int");

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdReceitaMedicaPadrao")
                        .HasName("PK__tbReceit__E6DF7D77D9F2691C");

                    b.HasIndex(new[] { "IdProfissional" }, "IX_tbReceitaMedicaPadrao_IdProfissional");

                    b.ToTable("tbReceitaMedicaPadrao");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbSubstancia", b =>
                {
                    b.Property<int>("IdSubstancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubstancia"));

                    b.Property<string>("InformacaoComplementar")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdSubstancia")
                        .HasName("PK__tbSubsta__13276D321A469721");

                    b.ToTable("tbSubstancia");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbSuplemento", b =>
                {
                    b.Property<int>("IdSuplemento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSuplemento"));

                    b.Property<double>("Carboidrato")
                        .HasColumnType("float");

                    b.Property<double>("DoseMaxima")
                        .HasColumnType("float");

                    b.Property<double>("DoseMinima")
                        .HasColumnType("float");

                    b.Property<int>("IdTipoQuantidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("VitaminaA")
                        .HasColumnType("float");

                    b.Property<double>("VitaminaB")
                        .HasColumnType("float");

                    b.HasKey("IdSuplemento")
                        .HasName("PK__tbSuplem__EC3A6B160D0E538F");

                    b.ToTable("tbSuplemento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbTipoAcesso", b =>
                {
                    b.Property<int>("IdTipoAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoAcesso"));

                    b.Property<bool>("FlagAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTipoAcesso")
                        .HasName("PK__tbTipoAc__FFC17AE5BEE97553");

                    b.ToTable("tbTipoAcesso");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbTipoProfissional", b =>
                {
                    b.Property<int>("IdTipoProfissional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProfissional"));

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTipoProfissional")
                        .HasName("PK__tbTipoPr__358F03BEAA1B9B6E");

                    b.ToTable("tbTipoProfissional");
                });

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetRoleClaims", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.AspNetRoles", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUserClaims", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUserLogins", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUserTokens", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbAntropometria", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbAntropometria")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbAntropo__IdHor__02FC7413");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbAntropometria")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbAntropo__IdPac__03F0984C");

                    b.Navigation("IdHoraPacienteProfissionalNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbCidade", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbEstado", "IdEstadoNavigation")
                        .WithMany("TbCidade")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__tbCidade__IdEsta__3C69FB99");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbContrato", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPlano", "IdPlanoNavigation")
                        .WithMany("TbContrato")
                        .HasForeignKey("IdPlano")
                        .IsRequired()
                        .HasConstraintName("FK__tbContrat__IdPla__412EB0B6");

                    b.Navigation("IdPlanoNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEscalaBristolPacienteConsulta", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbEscalaBristol", "IdEscalaBristolNavigation")
                        .WithMany("TbEscalaBristolPacienteConsulta")
                        .HasForeignKey("IdEscalaBristol")
                        .IsRequired()
                        .HasConstraintName("FK__tbEscalaB__IdEsc__17F790F9");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbEscalaBristolPacienteConsulta")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbEscalaB__IdHor__19DFD96B");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbEscalaBristolPacienteConsulta")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbEscalaB__IdPac__18EBB532");

                    b.Navigation("IdEscalaBristolNavigation");

                    b.Navigation("IdHoraPacienteProfissionalNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEstado", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPais", "IdPaisNavigation")
                        .WithMany("TbEstado")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK__tbEstado__IdPais__398D8EEE");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbExameFisico", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbExameFisico")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .HasConstraintName("FK__tbExameFi__IdHor__7A672E12");

                    b.Navigation("IdHoraPacienteProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbExameXPacientes", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbExame", "IdExameNavigation")
                        .WithMany("TbExameXPacientes")
                        .HasForeignKey("IdExame")
                        .IsRequired()
                        .HasConstraintName("FK__tbExame_X__IdExa__08B54D69");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbExameXPacientes")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbExame_X__IdPac__09A971A2");

                    b.Navigation("IdExameNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbGrupoPatologicoXPatologia", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbGrupoPatologico", "IdGrupoPatologicoNavigation")
                        .WithMany("TbGrupoPatologicoXPatologia")
                        .HasForeignKey("IdGrupoPatologico")
                        .IsRequired()
                        .HasConstraintName("FK__tbGrupoPa__IdGru__5070F446");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPatologia", "IdPatologiaNavigation")
                        .WithMany("TbGrupoPatologicoXPatologia")
                        .HasForeignKey("IdPatologia")
                        .IsRequired()
                        .HasConstraintName("FK__tbGrupoPa__IdPat__5165187F");

                    b.Navigation("IdGrupoPatologicoNavigation");

                    b.Navigation("IdPatologiaNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoriaPatologica", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoriaPatologica")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbHistori__IdPac__76969D2E");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPatologia", "IdPatologiaNavigation")
                        .WithMany("TbHistoriaPatologica")
                        .HasForeignKey("IdPatologia")
                        .HasConstraintName("FK__tbHistori__IdPat__778AC167");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdPatologiaNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoricoAlimentarNutricional", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoricoAlimentarNutricional")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbHistori__IdPac__00200768");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoricoDoencaAtual", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoricoDoencaAtual")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbHistori__IdPac__72C60C4A");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPatologia", "IdPatologiaNavigation")
                        .WithMany("TbHistoricoDoencaAtual")
                        .HasForeignKey("IdPatologia")
                        .HasConstraintName("FK__tbHistori__IdPat__73BA3083");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdPatologiaNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHistoricoSocialAlimentar", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHistoricoSocialAlimentar")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbHistori__IdPac__7D439ABD");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbHoraPacienteProfissional")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbHoraPac__IdPac__6EF57B66");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbHoraPacienteProfissional")
                        .HasForeignKey("IdProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbHoraPac__IdPro__6FE99F9F");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbLancarReceitasDespesas", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbGruposReceitasDespesas", "IdReceitaDespesaNavigation")
                        .WithMany("TbLancarReceitasDespesas")
                        .HasForeignKey("IdReceitaDespesa")
                        .IsRequired()
                        .HasConstraintName("FK__tbLancarR__IdRec__1EA48E88");

                    b.Navigation("IdReceitaDespesaNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbMedicamento", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbCategoriaMedicamento", "IdCategoriaMedicamentoNavigation")
                        .WithMany("TbMedicamento")
                        .HasForeignKey("IdCategoriaMedicamento")
                        .IsRequired()
                        .HasConstraintName("FK__tbMedicam__IdCat__5812160E");

                    b.Navigation("IdCategoriaMedicamentoNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbMedicoPaciente", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPaciente", "IdPacienteNavigation")
                        .WithMany("TbMedicoPaciente")
                        .HasForeignKey("IdPaciente")
                        .IsRequired()
                        .HasConstraintName("FK__tbMedico___IdPac__6B24EA82");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbMedicoPaciente")
                        .HasForeignKey("IdProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbMedico___IdPro__6C190EBB");

                    b.Navigation("IdPacienteNavigation");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPaciente", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany("TbPaciente")
                        .HasForeignKey("IdCidade")
                        .HasConstraintName("FK__tbPacient__IdCid__68487DD7");

                    b.Navigation("IdCidadeNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPergunta", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbPergunta")
                        .HasForeignKey("IdProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbPergunt__IdPro__0C85DE4D");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbProfissional", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbCidade", "IdCidadeNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdCidade")
                        .IsRequired()
                        .HasConstraintName("FK__tbProfiss__IdCid__49C3F6B7");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbContrato", "IdContratoNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdContrato")
                        .IsRequired()
                        .HasConstraintName("FK__tbProfiss__IdCon__47DBAE45");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbTipoAcesso", "IdTipoAcessoNavigation")
                        .WithMany("TbProfissional")
                        .HasForeignKey("IdTipoAcesso")
                        .HasConstraintName("FK__tbProfiss__IdTip__48CFD27E");

                    b.Navigation("IdCidadeNavigation");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdTipoAcessoNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbRastreamentoMetabolico", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", "IdHoraPacienteProfissionalNavigation")
                        .WithMany("TbRastreamentoMetabolico")
                        .HasForeignKey("IdHoraPacienteProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbRastrea__IdHor__1332DBDC");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbRastreamentoResposta", "IdRastreamentoRespostaNavigation")
                        .WithMany("TbRastreamentoMetabolico")
                        .HasForeignKey("IdRastreamentoResposta")
                        .IsRequired()
                        .HasConstraintName("FK__tbRastrea__IdRas__123EB7A3");

                    b.Navigation("IdHoraPacienteProfissionalNavigation");

                    b.Navigation("IdRastreamentoRespostaNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbRastreamentoResposta", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbPergunta", "IdPerguntaNavigation")
                        .WithMany("TbRastreamentoResposta")
                        .HasForeignKey("IdPergunta")
                        .IsRequired()
                        .HasConstraintName("FK__tbRastrea__IdPer__0F624AF8");

                    b.Navigation("IdPerguntaNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaAlimentarPadrao", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbReceitaAlimentarPadrao")
                        .HasForeignKey("IdProfissional")
                        .HasConstraintName("FK__tbReceita__IdPro__5EBF139D");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaAlimentarPadraoXAlimento", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbAlimento", "IdAlimentoNavigation")
                        .WithMany("TbReceitaAlimentarPadraoXAlimento")
                        .HasForeignKey("IdAlimento")
                        .IsRequired()
                        .HasConstraintName("FK__tbReceita__IdAli__656C112C");

                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbReceitaAlimentarPadrao", "IdReceitaAlimentarPadraoNavigation")
                        .WithMany("TbReceitaAlimentarPadraoXAlimento")
                        .HasForeignKey("IdReceitaAlimentarPadrao")
                        .IsRequired()
                        .HasConstraintName("FK__tbReceita__IdRec__6477ECF3");

                    b.Navigation("IdAlimentoNavigation");

                    b.Navigation("IdReceitaAlimentarPadraoNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaMedicaPadrao", b =>
                {
                    b.HasOne("Projeto1_Web2_IF_johnnata.Models.TbProfissional", "IdProfissionalNavigation")
                        .WithMany("TbReceitaMedicaPadrao")
                        .HasForeignKey("IdProfissional")
                        .IsRequired()
                        .HasConstraintName("FK__tbReceita__IdPro__619B8048");

                    b.Navigation("IdProfissionalNavigation");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetRoles", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.AspNetUsers", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbAlimento", b =>
                {
                    b.Navigation("TbReceitaAlimentarPadraoXAlimento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbCategoriaMedicamento", b =>
                {
                    b.Navigation("TbMedicamento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbCidade", b =>
                {
                    b.Navigation("TbPaciente");

                    b.Navigation("TbProfissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbContrato", b =>
                {
                    b.Navigation("TbProfissional");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEscalaBristol", b =>
                {
                    b.Navigation("TbEscalaBristolPacienteConsulta");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbEstado", b =>
                {
                    b.Navigation("TbCidade");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbExame", b =>
                {
                    b.Navigation("TbExameXPacientes");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbGrupoPatologico", b =>
                {
                    b.Navigation("TbGrupoPatologicoXPatologia");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbGruposReceitasDespesas", b =>
                {
                    b.Navigation("TbLancarReceitasDespesas");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbHoraPacienteProfissional", b =>
                {
                    b.Navigation("TbAntropometria");

                    b.Navigation("TbEscalaBristolPacienteConsulta");

                    b.Navigation("TbExameFisico");

                    b.Navigation("TbRastreamentoMetabolico");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPaciente", b =>
                {
                    b.Navigation("TbAntropometria");

                    b.Navigation("TbEscalaBristolPacienteConsulta");

                    b.Navigation("TbExameXPacientes");

                    b.Navigation("TbHistoriaPatologica");

                    b.Navigation("TbHistoricoAlimentarNutricional");

                    b.Navigation("TbHistoricoDoencaAtual");

                    b.Navigation("TbHistoricoSocialAlimentar");

                    b.Navigation("TbHoraPacienteProfissional");

                    b.Navigation("TbMedicoPaciente");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPais", b =>
                {
                    b.Navigation("TbEstado");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPatologia", b =>
                {
                    b.Navigation("TbGrupoPatologicoXPatologia");

                    b.Navigation("TbHistoriaPatologica");

                    b.Navigation("TbHistoricoDoencaAtual");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPergunta", b =>
                {
                    b.Navigation("TbRastreamentoResposta");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbPlano", b =>
                {
                    b.Navigation("TbContrato");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbProfissional", b =>
                {
                    b.Navigation("TbHoraPacienteProfissional");

                    b.Navigation("TbMedicoPaciente");

                    b.Navigation("TbPergunta");

                    b.Navigation("TbReceitaAlimentarPadrao");

                    b.Navigation("TbReceitaMedicaPadrao");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbRastreamentoResposta", b =>
                {
                    b.Navigation("TbRastreamentoMetabolico");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbReceitaAlimentarPadrao", b =>
                {
                    b.Navigation("TbReceitaAlimentarPadraoXAlimento");
                });

            modelBuilder.Entity("Projeto1_Web2_IF_johnnata.Models.TbTipoAcesso", b =>
                {
                    b.Navigation("TbProfissional");
                });
#pragma warning restore 612, 618
        }
    }
}
